export const REQUEST_MOVIE_LIST = 'REQUEST_MOVIE_LIST';
export const REQUEST_MOVIE_SUCCESS = 'REQUEST_MOVIE_SUCCESS';
export const REQUEST_MOVIE_FAILED = 'REQUEST_MOVIE_FAILED';
export const ADD_MOVIE = 'ADD_MOVIE';
